### ISSUE TITLE
help wanted: how to know EPACTS version used?

### ISSUE THREAD

**Issue by complexgenome** [statgen/EPACTS#17]
Hi team,

I'd like to know the version I'm using but none of the following commands help:

```
epacts --version

epacts -version

epacts -v

epacts --v

epacts man

epacts help
```

Thanks!

**Comment by jonathonl** [comment]
The first version to include this ability is https://github.com/statgen/EPACTS/releases/tag/v3.4.2. It is implemented as a sub command `epacts version` and will be displayed with the help output in the next release.

**Comment by complexgenome** [comment]
Thanks, I don't know which version of EPACTS I'm using :-/

**Comment by jonathonl** [comment]
Relative to where you have EPACTS installed, there is a file at lib/epactsR/DESCRIPTION that will contain the version. If you run `which epacts` and the output is /usr/local/bin/epacts then the description file will be at /usr/local/lib/epactsR/DESCRIPTION.

**Comment by complexgenome** [comment]
Awesome, it helps.  :)
