### ISSUE TITLE
Add passive mode to FTP connection

### ISSUE THREAD

**Issue by vdejager** [statgen/EPACTS#25]
https://github.com/statgen/EPACTS/blob/edc39656dec3369a168315bfee128d617dde1135/scripts/epacts-download#L31

Please note that passive mode could be used to download the refs in case of difficulties running epacts from within a singularity container.
my $ftp = Net::FTP->new("$hostname", Debug => 0, Passive => 1) or die "Cannot connect to $hostname $@";

**Comment by jonathonl** [comment]
This is already fixed in the develop branch. See 52229c0f5a18f2a3bc4ba6b9c12645347c17fab0
